/* Criar o banco de dados */

CREATE DATABASE LIVRARIA;

USE LIVRARIA;
/* Criando uma tabela */
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(100),
    NOME_AUTOR VARCHAR(100),
    SEXO_AUTOR CHAR(1),
    NUMERO_PAGINAS INT,
    EDITORA VARCHAR(50),
    ESTADO_EDITORA CHAR(2),
    ISBN VARCHAR(11),
    VALOR DECIMAL(18,6)
);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS, EDITORA,ESTADO_EDITORA, ISBN, VALOR) VALUES ('LIVRO DE JAVA','FRANCISCO SOUZA', 'M',256,'NOVATEC','SP', '12589636975', '22.54');
INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS, EDITORA,ESTADO_EDITORA, ISBN, VALOR) VALUES ('LIVRO DE C','RENATA PELLES','M', 508 ,'PACKET', 'RJ','25130398752', '55.54');
INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS, EDITORA,ESTADO_EDITORA, ISBN, VALOR) VALUES ('LIVRO DE SQL', 'GEREMIAS BARTOLOMEU', 'M',366,'AMAZON','BA', '3658752145', '78.96');
INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS, EDITORA,ESTADO_EDITORA, ISBN, VALOR) VALUES ('LIVRO DE MODELAGEM', 'MARIA MADALENA', 'F',256,'NOVATEC','SP', '65236987452', '35.10');

/*Trazer Todos os dados*/
SELECT NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS, EDITORA,ESTADO_EDITORA, ISBN, VALOR FROM LIVROS;

/*TRAZER NOME DO LIVRO E NOME DA EDITORA*/

SELECT NOME_LIVRO AS 'NOME DO LIVRO', EDITORA AS 'NOME DA EDITORA' FROM LIVROS;

/* TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO*/
SELECT NOME_LIVRO AS 'NOME DO LIVRO', ESTADO_EDITORA AS 'ESTADO DA EDITORA' FROM LIVROS WHERE SEXO_AUTOR = 'M';

/* TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO*/
SELECT NOME_LIVRO AS 'NOME DO LIVRO', ESTADO_EDITORA AS 'ESTADO DA EDITORA' FROM LIVROS WHERE SEXO_AUTOR = 'F';

/*TRAZER O VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO*/
SELECT VALOR FROM LIVROS WHERE ESTADO_EDITORA = 'SP';

/* TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SP OU RJ */
SELECT NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS, EDITORA,ESTADO_EDITORA, ISBN, VALOR FROM LIVROS WHERE SEXO_AUTOR = 'M'
AND (ESTADO_EDITORA = 'SP' OR ESTADO_EDITORA = 'RJ');
 
